name: Step_types

on:
  workflow_dispatch:

jobs:
  say-hello_from_bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Again $NAME Hello World new Skill see the next jobs to get to know "
        env:
          NAME: BAVTIH

  say-Hello-from-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello there iam from python shell i think job 1 , Had told told about me ")
        shell: python
  
  say-Hello-from-java-Script-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d # v1.1
        with: 
          who-to-greet: "from an action in github action market action Place"
  