name: Environmental Passing 

on:
 workflow_dispatch:

env:
    WORKFLOW_VAR: Hey Iam Gloabal variable

jobs:
    job-1:
     runs-on: ubuntu-latest
     env:
        JOB1_VAR: This is can be visible in only job-1
     steps:
        - name: Job-1 Step 1 
          env:
            STEP1_VAR: I am only valide for job-1 step
          run : |
            echo "This is global varibale: $WORKFLOW_VAR" 
            echo "This is varible is from job-1: $JOB1_VAR"
            echo "This vaiable is for only for this steps : $STEP1_VAR"

        - name: Job-1 step 2
          run : |
            echo "This is global variable can be used:$WORKFLOW_VAR"
            echo "This variable is from Job-1 so usabel$JOB1_VAR"
            echo "This is from Step-1 can't be used :$STEP1_VAR"
    
    job-2:
     runs-on: ubuntu-latest
     env:
        JOB2_VAR: This is job2 variable 
     steps:
        - name: Job-2 Steps
          run: |
           echo "Hello This is job2 lets print the global variable $WORKFLOW_VAR"
           echo "So we try to use the Job-1 variable $JOB1_VAR"
           echo "Let us our varible $JOB2_VAR"

